# Generated by Django 6.0.2 on 2026-02-10 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bulkinquiry',
            name='products',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
